### ISSUE TITLE
json codec support for consuming and publishing Feature

### ISSUE THREAD

**Issue by yisraelU** [svroonland/zio-amqp#181]
perhaps support multiple JSON codec libs (zio-json,circe,play-json)
basically a typeclass for round-tripping from ADT's to Array[Byte] and allow for calling publish directly on any value or consume and return ZStream[Any,Throwable,A]

**Comment by svroonland** [comment]
Good use case.

There's a bunch of json libs out there and everybody has their favourite. The (de)serialization step is usually a oneliner mapM(...) in the stream.

How about instead of picking one or creating many variants of zio-amqp-circe subprojects, we make an examples project showing how to use your favourite json libs together with zio-amqp?
